services:
  app.dice.twelve.factory:
      class: AppBundle\Factory\TwelveSidedDiceFactory
      arguments:
        - "@app.dice.provider.numeric"

  app.dice.provider.numeric:
    class: AppBundle\Service\NumericValueProvider

  app.dice.six:
    class:  AppBundle\Service\SixSidedDice
    autowiring_types: AppBundle\Service\DiceInterface
    tags:
      -  { name: app.dice.provider.aware }

  app.dice.twelve:
    class: AppBundle\Service\TwelveSidedDice
    factory: ["@app.dice.twelve.factory", createTwelveSidedDice]
    tags:
      -  { name: app.rollable }

  app.dice_controller:
    class: AppBundle\Controller\DiceController
    autowire: true
    calls:
      - [setContainer, ['@service_container']]
